<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Automation smoke Test" duration-ms="59944" started-at="2017-02-21T04:55:56Z" finished-at="2017-02-21T04:56:56Z">
    <groups>
    </groups>
    <test name="templete test class" duration-ms="14" started-at="2017-02-21T04:55:56Z" finished-at="2017-02-21T04:55:56Z">
      <class name="com.test.testcase.sample.TestTempleteTestCase">
        <test-method status="FAIL" signature="beforeTest(java.lang.String)[pri:0, instance:com.test.testcase.sample.TestTempleteTestCase@21588de9]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-02-21T12:55:56Z" finished-at="2017-02-21T12:55:56Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method beforeTest requires 1 parameters but 2 were supplied in the @Configuration annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method beforeTest requires 1 parameters but 2 were supplied in the @Configuration annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:358)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:86)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:199)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testLogin(java.lang.Object)[pri:0, instance:com.test.testcase.sample.TestTempleteTestCase@21588de9]" name="testLogin" duration-ms="0" started-at="2017-02-21T12:55:56Z" data-provider="createMapObj" finished-at="2017-02-21T12:55:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:149)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:com.test.testcase.sample.TestTempleteTestCase@21588de9]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-02-21T12:55:56Z" finished-at="2017-02-21T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.test.testcase.sample.TestTempleteTestCase -->
    </test> <!-- templete test class -->
    <test name="test fixture " duration-ms="59902" started-at="2017-02-21T04:55:56Z" finished-at="2017-02-21T04:56:56Z">
      <class name="com.test.testcase.TestActionFixture">
        <test-method status="PASS" signature="beforeTest(java.lang.String, java.lang.String)[pri:0, instance:com.test.testcase.TestActionFixture@323f6c10]" name="beforeTest" is-config="true" duration-ms="5399" started-at="2017-02-21T12:55:56Z" finished-at="2017-02-21T12:56:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[templete.xls]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[totalelement;firstpage]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testAction()[pri:0, instance:com.test.testcase.TestActionFixture@323f6c10]" name="testAction" duration-ms="53266" started-at="2017-02-21T12:56:02Z" finished-at="2017-02-21T12:56:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Multiple failures (2):

Failure 1 of 2:
java.lang.RuntimeException: can't find the element of the key or can't open URL 
	at com.test.fixture.ActionFixture.dowRows(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.testcase.TestActionFixture.test(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.test.basetest.BaseTest.invokeMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.testcase.TestActionFixture.testAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)


Failure 2 of 2:
java.lang.RuntimeException: can't find the element of the key or can't open URL ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Multiple failures (2):

Failure 1 of 2:
java.lang.RuntimeException: can't find the element of the key or can't open URL 
	at com.test.fixture.ActionFixture.dowRows(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.testcase.TestActionFixture.test(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.test.basetest.BaseTest.invokeMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.testcase.TestActionFixture.testAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)


Failure 2 of 2:
java.lang.RuntimeException: can't find the element of the key or can't open URL 
	at com.test.fixture.ActionFixture.dowRows(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.fixture.ActionFixture.doSheet(Unknown Source)
	at com.test.testcase.TestActionFixture.test(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.test.basetest.BaseTest.invokeMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.basetest.BaseTest.testMethod(Unknown Source)
	at com.test.testcase.TestActionFixture.testAction(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAction -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.test.testcase.TestActionFixture@323f6c10]" name="afterTest" is-config="true" duration-ms="1234" started-at="2017-02-21T12:56:55Z" finished-at="2017-02-21T12:56:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.test.testcase.TestActionFixture -->
      <class name="com.test.testcase.sample.TestTempleteTestCase">
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.test.testcase.sample.TestTempleteTestCase@21588de9]" name="afterSuite" is-config="true" duration-ms="0" started-at="2017-02-21T12:56:57Z" finished-at="2017-02-21T12:56:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.testcase.sample.TestTempleteTestCase -->
    </test> <!-- test fixture  -->
  </suite> <!-- Automation smoke Test -->
</testng-results>
